version: "3"

services:
  prod_api:
    build:
      context: .
      target: production
    env_file:
      - ./.env
    ports:
      - 5000:5000
      # env_file:
      #   - ./.env
      # args:
      #   NODE_ENV: production
      # environment:
      #   - NODE_ENV=production
    # command: node build/index.js
